import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [ 
    'intro',
    {
      type: 'category',
      label: 'Artificial Intelligence', 
      link: {
        type: 'generated-index',
        title: 'Artificial Intelligence',
        keywords: ['Artificial Intelligence','ai'],
      },
      items: [
        {
          type: 'category',
          label: 'Stable Diffusion', 
          link: {
            type: 'generated-index',
            title: 'Stable Diffusion',
            keywords: ['stable-diffusion'],
          },
          items: [{type: 'autogenerated', dirName: 'artificial-intelligence/stable-diffusion'}] 
        },
      ] 
    },
    {
      type: 'category',
      label: 'Programming Langauge', 
      link: {
        type: 'generated-index',
        title: 'Programming Langauge',
        keywords: ['langauge'],
      },
      items: [
        {
          type: 'category',
          label: 'C#', 
          link: {
            type: 'generated-index',
            title: 'C#',
            keywords: ['c#'],
          },
          items: [{type: 'autogenerated', dirName: 'programming-langauge/c-sharp'}] 
        },
        {
          type: 'category',
          label: 'JavaScript', 
          link: {
            type: 'generated-index',
            title: 'JavaScript',
            keywords: ['javascript','js'],
          },
          items: [{type: 'autogenerated', dirName: 'programming-langauge/javascript'}] 
        }
      ] 
    },
    {
      type: 'category',
      label: 'Cloud', 
      link: {
        type: 'generated-index',
        title: 'Cloud',
        keywords: ['cloud'],
      },
      items: [
        {
          type: 'category',
          label: 'Azure', 
          link: {
            type: 'generated-index',
            title: 'Azure',
            keywords: ['azure'],
          },
          items: [{type: 'autogenerated', dirName: 'cloud/azure'}] 
        }
      ] 
    },
    {
      type: 'category',
      label: 'React', 
      link: {
        type: 'generated-index',
        title: 'React',
        keywords: ['react'],
      },
      items: [{type: 'autogenerated', dirName: 'react'}] 
    },
    {
      type: 'category',
      label: '.NET', 
      link: { 
        type: 'generated-index',
        title: '.NET',
        keywords: ['.net'],
      },
      items: [{type: 'autogenerated', dirName: 'dotNet'}] 
    }
  ],
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
